<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>efe44acf-d888-4f2c-8aeb-91dc1f2d323a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContrleLicenca.Api.Services.Movimentacao\ControleLicenca.Api.Services.Movimentacao.csproj" />
    <ProjectReference Include="..\ControleLicenca.Api.Cadastro\ControleLicenca.Api.Services.Cadastro.csproj" />
    <ProjectReference Include="..\ControleLicenca.Api.Repositorios\ControleLicenca.Api.Repositorios.csproj" />
    <ProjectReference Include="..\ControleLicenca.Context\ControleLicenca.Modelo.Context.csproj" />
    <ProjectReference Include="..\ControleLicenca.DTOs\ControleLicenca.Modelo.DTOs.csproj" />
    <ProjectReference Include="..\ControleLicenca.Entidades\ControleLicenca.Modelo.Entidades.csproj" />
    <ProjectReference Include="..\ControleLicenca.Modelo\ControleLicenca.Modelo.csproj" />
  </ItemGroup>

</Project>
